### ISSUE TITLE
Error while assigning roles

### ISSUE THREAD

**Issue by joshisimt** [akgup/keycloak-springboot#7]
Hi @akgup 

Thanks for explain this.
I am getting below error when I am try to assign the user role to created user.

`Unrecognized field "attributes" (class org.keycloak.representations.idm.RoleRepresentation), not marked as ignorable (8 known properties: "clientRole", "composite", "scopeParamRequired", "id", "description", "name", "composites", "containerId"])
 at [Source: org.apache.http.conn.EofSensorInputStream@57f53b0a; line: 1, column: 155] (through reference chain: org.keycloak.representations.idm.RoleRepresentation["attributes"]`

`				RealmResource realmResource = getRealmResource();
				RoleRepresentation savedRoleRepresentation = realmResource.roles().get("user").toRepresentation();
				realmResource.users().get(userId).roles().realmLevel().add(Arrays.asList(savedRoleRepresentation));
`

User roles is already present under roles.
can you please help?

Thanks

**Comment by joshisimt** [comment]
Closing this as I have  resolved this.

Thanks

**Comment by ivancorroto** [comment]
Hi, 

I have the same problem.

How do you resolved it?

Tnhaks

**Comment by beulahpt** [comment]
I am also facing the same issue. How did you fix this?
